# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('SecondName', models.CharField(max_length=20)),
                ('LastName', models.CharField(blank=True, max_length=20)),
                ('Icon', models.ImageField(upload_to='')),
                ('Creation', models.DateTimeField()),
            ],
        ),
    ]
